### ISSUE TITLE
Use existing `$ANDROID_HOME` instead of creating our own?

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/andromatic#3]
Currently, we are always creating our own `$ANDROID_HOME` regardless of whether the user already has one:

https://github.com/tweaselORG/andromatic/blob/8024d5194296a690239dd1d78637d6be6487b8e2/src/index.ts#L106

https://github.com/tweaselORG/andromatic/blob/8024d5194296a690239dd1d78637d6be6487b8e2/README.md?plain=1#L16

My main thinking for that was not to interfere with the user's existing Android SDK installation as they may not want additional things installed there.

But if the user already has some (or all) of the packages downloaded, we'll redownload them unnecessarily.

Maybe we should use the user's existing `$ANDROID_HOME` if the env var is set? Not sure.

**Comment by baltpeter** [comment]
My main reason for opening this issue was that I thought we would have a problem with emulator AVDs. But that's actually _not_ the case. Emulator AVDs don't have anything to do with `$ANDROID_HOME`. They are always [stored in `$HOME/.android/avd`](https://stackoverflow.com/a/13095728).

I just ran `emulator -list-avds` through andromatic and it listed all the AVDs I created using a different SDK.

**Comment by baltpeter** [comment]
After an `await installPackages('system-images;android-33;google_apis;x86_64', 'platforms;android-33');`, I was also able to start the emulator through andromatic.

EDIT: Actually, I would guess that the `system-images` package would only have been necessary to create a new emulator, not to start an existing one. The error I got was `WARNING | platforms subdirectory is missing under /home/benni/.cache/andromatic, please install it`, and installing the `system-images` package didn't resolve that.

**Comment by baltpeter** [comment]
> Emulator AVDs don't have anything to do with `$ANDROID_HOME`. They are always [stored in `$HOME/.android/avd`](https://stackoverflow.com/a/13095728).

[That can be overridden with `$ANDROID_AVD_HOME`](https://developer.android.com/tools/variables#android_emulator_home), which is great because we don't touch that. So nothing to worry about on that front.

**Comment by baltpeter** [comment]
@zner0L We should probably make a decision here before the first release.

**Comment by zner0L** [comment]
I think the purpose of this package is to provide a consistent API for the Android command line tools. And for that I think using our own `$ANDROID_HOME` is better. We also create our own venv even if mitmproxy might be installed already. I think, as long as we document this clearly, this is better than trying to manage user installed binaries. The only thing that I am still a little vary of is updating outdated versions of the tools.
