### ISSUE TITLE
`findJavaHome` returns wrong directory on macOS

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/andromatic#6]
I run macOS 12.6.5 and have an old `openjdk 11.0.10 2021-01-19` java version installed. `findJavaHome()` seems to return `/usr` as my `JAVA_HOME` instead of `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home`, which is my actual `JAVA_HOME`. This breaks `sdkmanager` so that it doesn‘t install packages, but it also doesn‘t exit.

Apparently, on macOS it is pretty easy to find the `JAVA_HOME` using `/usr/libexec/java_home` (https://stackoverflow.com/questions/22842743/how-to-set-java-home-environment-variable-on-mac-os-x-10-9)

**Comment by baltpeter** [comment]
> Apparently, on macOS it is pretty easy to find the `JAVA_HOME` using `/usr/libexec/java_home`

That library should already be using that: https://github.com/jsdevel/node-find-java-home/blob/f59541128bea7cfbe9af5a8b4eb58ff2a5291c5e/src/index.ts#L111

**Comment by baltpeter** [comment]
Do you have a `/usr/bin/java` in your `PATH`? If I read the code correctly, that would make the library return `/usr`.

**Comment by baltpeter** [comment]
Oh, there's a long-standing issue: https://github.com/jsdevel/node-find-java-home/issues/29

**Comment by zner0L** [comment]
> Do you have a /usr/bin/java in your PATH? If I read the code correctly, that would make the library return /usr.

Yes, exactly. It is not symlinked, but the library assumes it is. I guess I‘ll open a PR, but not today.

**Comment by baltpeter** [comment]
Potential alternative: https://github.com/viperproject/locate-java-home

**Comment by baltpeter** [comment]
@zner0L Do you want to work on this or should I?

**Comment by zner0L** [comment]
I tested https://github.com/viperproject/locate-java-home: It found installed Java JDKs on maOS, Linux and Windows (though on Windows I needed to install the Adoptium JDK with the option to set the `JAVA_HOME` env variable, which is not the default apparently). I think we should switch.
